### ISSUE TITLE
How to add Mutiple Labels in pin issue yaml file based on Github Action 

### ISSUE THREAD

**Issue by mohdrashid1** [bdougie/issue-pin-by-label#19]
Hi All,

I'm having issue with Pin Issue based on Labels getting error when i create a new Issues in github repo after selecting labels into that i got github action job fail and error is below one

Please set up a LABEL_NAME environment variable in the main.workflow file

and Here is my pin.yaml file
```
# .github/workflows/pin.yml 
on: 
  issues:
    types: [labeled]
name: pin issue based on label
jobs:
  pinAnIssue:
    name: pin an issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pin an issue
      uses: bdougie/issue-pin-by-label@v4.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL_NAME: blocker 
```
I want to know how to add mutiple labels in my pin.yaml file please tell me
